### ISSUE TITLE
wxWindows returns a 404

### ISSUE THREAD

**Issue by alandtse** [spdx/spdx-website#3]
This impacts pages:

- https://spdx.org/licenses/wxWindows.html
- https://spdx.org/licenses/wxWindows.json

**Comment by goneall** [comment]
@swinslow I check the license list data and it looks like the files were generated correctly.  Can you check the AWS s3 bucket and see if the html files were copied over correctly?

**Comment by swinslow** [comment]
Thanks for catching this... here's what it looks like happened:

* the files used to be hosted from a Linux-based server, on a case-sensitive filesystem
* for this update, I was unpacking the files onto my local system before pushing them to an S3 bucket
* my local system is running Mac OS X with a *case-insensitive* filesystem
* there were old files named "WXwindows.html" already in the pre-existing directory, which is not the correct capitalization per the license list.

So when unpacking the license-list-data files before pushing to S3, it was failing to create e.g. "wxWindows.html" because the case-insensitive OSX filesystem was collapsing it together with "WXwindows.html".

I've now removed the old capitalization files and reinserted the correct ones, so this should be fixed now. Very odd behavior but it doesn't look like it's affecting any other licenses, so hopefully we won't see a recurrence of this!

**Comment by alandtse** [comment]
Looks fixed to me. Thanks!
